In [186]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [187]:
df = pd.read_csv("players.csv")
df.head()

Name  Jersey Number     Club    Position Nationality   Age  \
0            Bernd Leno            1.0  Arsenal  Goalkeeper     Germany  28.0   
1            Matt Macey           33.0  Arsenal  Goalkeeper     England  26.0   
2  Rúnar Alex Rúnarsson           13.0  Arsenal  Goalkeeper     Iceland  25.0   
3       Héctor Bellerín            2.0  Arsenal    Defender       Spain  25.0   
4        Kieran Tierney            3.0  Arsenal    Defender    Scotland  23.0   

   Appearances  Wins  Losses  Penalties scored  ...  Successful 50/50s  \
0           64    28      16               NaN  ...                NaN   
1            0     0       0               NaN  ...                NaN   
2            0     0       0               NaN  ...                NaN   
3          160    90      37               NaN  ...              196.0   
4           16     7       5               NaN  ...               12.0   

   Assists  Passes Big chances created  Crosses  Yellow cards  Red cards  \
0        0    1783                 NaN      NaN             2          0   
1        0       0                 NaN      NaN             0          0   
2        0       0                 NaN      NaN             0          0   
3       18    7125                28.0    389.0            23          0   
4        1     519                 1.0     45.0             2          0   

   Fouls  Offsides  Goals  
0      0       NaN      0  
1      0       NaN      0  
2      0       NaN      0  
3    125       8.0      7  
4      9       0.0      1  

[5 rows x 26 columns]

In [188]:
df.fillna(0, inplace=True) #Filling all blank entries with 0 (even string coolumns)
df.head()

Name  Jersey Number     Club    Position Nationality   Age  \
0            Bernd Leno            1.0  Arsenal  Goalkeeper     Germany  28.0   
1            Matt Macey           33.0  Arsenal  Goalkeeper     England  26.0   
2  Rúnar Alex Rúnarsson           13.0  Arsenal  Goalkeeper     Iceland  25.0   
3       Héctor Bellerín            2.0  Arsenal    Defender       Spain  25.0   
4        Kieran Tierney            3.0  Arsenal    Defender    Scotland  23.0   

   Appearances  Wins  Losses  Penalties scored  ...  Successful 50/50s  \
0           64    28      16               0.0  ...                0.0   
1            0     0       0               0.0  ...                0.0   
2            0     0       0               0.0  ...                0.0   
3          160    90      37               0.0  ...              196.0   
4           16     7       5               0.0  ...               12.0   

   Assists  Passes Big chances created  Crosses  Yellow cards  Red cards  \
0        0    1783                 0.0      0.0             2          0   
1        0       0                 0.0      0.0             0          0   
2        0       0                 0.0      0.0             0          0   
3       18    7125                28.0    389.0            23          0   
4        1     519                 1.0     45.0             2          0   

   Fouls  Offsides  Goals  
0      0       0.0      0  
1      0       0.0      0  
2      0       0.0      0  
3    125       8.0      7  
4      9       0.0      1  

[5 rows x 26 columns]

In [189]:
X = df.iloc[:,3:-1].values #independent variables
X

array([['Goalkeeper', 'Germany', 28.0, ..., 0, 0, 0.0],
       ['Goalkeeper', 'England', 26.0, ..., 0, 0, 0.0],
       ['Goalkeeper', 'Iceland', 25.0, ..., 0, 0, 0.0],
       ...,
       ['Forward', 'Spain', 24.0, ..., 0, 80, 13.0],
       ['Forward', 'Portugal', 18.0, ..., 0, 0, 0.0],
       ['Forward', 'Ecuador', 20.0, ..., 0, 0, 0.0]], dtype=object)

In [190]:
y = df.iloc[:, -1].values #dependent variable
y

array([  0,   0,   0,   7,   1,   0,   3,   0,   7,   6,  13,   2,   1,
        33,   3,   1,   0,   1,   0,   0,   8,   1,   0,  39,  55,   5,
         1,   4,   3,  37,   0,   0,   0,   0,   0,   0,   2,   2,   1,
         0,   6,   1,   2,   0,   3,   3,   0,   9,   0,   3,   6,   4,
         0,   0,   5,   0,   0,   2,   0,   0,   0,   0,   0,   0,   6,
         3,   0,   0,   0,   0,   0,   0,   1,   1,   0,  12,  30,   2,
         2,   0,   0,   0,   0,   0,   6,  12,   2,   5,   4,   4,   0,
         0,   0,   0,   2,   0,   5,   4,   1,   7,   1,   1,   0,   0,
         8,   7,   0,   5,   9,   9,   0,  36,  38,  41,   6,   0,   0,
         5,  20,   0,   5,   1,   8,   1,   0,   4,   0,   0,   0,   7,
        10,  25,   9,   1,   7,   9,   0,   0,   0,  20,  86,   1,   0,
         0,   0,   0,   4,  20,  12,  15,   3,  27,   0,   0,   0,   0,
         0,  27,   1,  13,  22,  11,  23,  13,   0,   0,   0,  25,  39,
        72,  19,   0,  13,   0,   0,   0,   0,   6,   4,   3,  2

In [191]:
string_columns = df.iloc[:, 3:-1].select_dtypes(include=['object']).columns.tolist()
string_columns 

['Position', 'Nationality', 'Shooting accuracy %']

In [192]:
type(X)

numpy.ndarray

In [193]:
type(string_columns)

list

Implementing Encoding:

In [194]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

X_le = le.fit(X[:, 0])
print(X_le.classes_)
X_le = le.transform(X[:, 0])
print(X_le)

['Defender' 'Forward' 'Goalkeeper' 'Midfielder']
[2 2 2 0 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 2 2 2 2 2 0 0
 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 1 1 1 1 2 2 2 2 0 0 0 0 0 0 0 0 0 0 3 3
 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 2 2 2 0 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3
 1 1 1 1 2 2 0 0 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 1 1 1 1 2 2 2 0 0 0
 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 2 2 2 0 0 0 0 0 0 0 0 3
 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 2 2 2 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3
 3 3 3 1 1 1 1 2 2 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 2 2 2 0
 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 2 2 2 2 2 0 0 0 0 0
 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 1 1 1 1 1 1 1 1 2 2 2 0 0 0 0 0 0 0 0 0 3
 3 3 3 3 3 3 3 3 1 1 1 1 1 1 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3
 3 3 3 3 1 1 1 1 2 2 2 2 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 1 1 1 1
 1 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 1 1 1 1 2 2 2 2 0 0 0 0
 0 0 0 0 3 3 3 3 3 3 3 3 1 1 1 1 2 2 2 2 2 0 0 0 0 

In [195]:
X[:, 0] = X_le
X

array([[2, 'Germany', 28.0, ..., 0, 0, 0.0],
       [2, 'England', 26.0, ..., 0, 0, 0.0],
       [2, 'Iceland', 25.0, ..., 0, 0, 0.0],
       ...,
       [1, 'Spain', 24.0, ..., 0, 80, 13.0],
       [1, 'Portugal', 18.0, ..., 0, 0, 0.0],
       [1, 'Ecuador', 20.0, ..., 0, 0, 0.0]], dtype=object)

In [196]:
X

array([[2, 'Germany', 28.0, ..., 0, 0, 0.0],
       [2, 'England', 26.0, ..., 0, 0, 0.0],
       [2, 'Iceland', 25.0, ..., 0, 0, 0.0],
       ...,
       [1, 'Spain', 24.0, ..., 0, 80, 13.0],
       [1, 'Portugal', 18.0, ..., 0, 0, 0.0],
       [1, 'Ecuador', 20.0, ..., 0, 0, 0.0]], dtype=object)

In [197]:
X[:, 1] = X[:, 1].astype(str)
X[:, 1]

array(['Germany', 'England', 'Iceland', 'Spain', 'Scotland', 'France',
       'Greece', 'England', 'Germany', 'England', 'Brazil',
       'Bosnia And Herzegovina', 'Brazil', 'Germany', 'Uruguay',
       'England', 'Egypt', 'England', 'France', 'England', 'Switzerland',
       'England', 'Spain', 'France', 'Gabon', "Cote D'Ivoire", 'England',
       'England', 'Brazil', 'Brazil', 'England', 'England', 'Norway',
       'Croatia', 'Argentina', 'Wales', 'England', 'England', 'Belgium',
       'France', 'Egypt', 'England', 'England', 'England', 'Brazil',
       'Scotland', 'England', 'England', 'Zimbabwe', 'Ireland', 'Egypt',
       'Netherlands', 'Spain', 'England', 'Brazil', 'England', 'England',
       'Burkina Faso', 'Australia', 'England', 'England', 'Spain',
       'England', 'England', 'England', 'England', 'Brazil', 'England',
       'Netherlands', 'France', 'England', 'England', 'England', 'Mali',
       'Argentina', 'Germany', 'England', 'England', 'Netherlands',
       'Colombia'

In [198]:
le1 = LabelEncoder()
X_le = le1.fit(X[:, 1])
print(X_le.classes_)
X_le = le1.transform(X[:, 1])
print(X_le)
X[:, 1] = X_le
X

['0' 'Algeria' 'Argentina' 'Australia' 'Austria' 'Belgium'
 'Bosnia And Herzegovina' 'Brazil' 'Burkina Faso' 'Cameroon' 'Colombia'
 "Cote D'Ivoire" 'Croatia' 'Czech Republic' 'Denmark' 'Ecuador' 'Egypt'
 'England' 'France' 'Gabon' 'Germany' 'Ghana' 'Greece' 'Guinea' 'Iceland'
 'Iran' 'Ireland' 'Italy' 'Jamaica' 'Japan' 'Mali' 'Mexico' 'Morocco'
 'Netherlands' 'New Zealand' 'Nigeria' 'Northern Ireland' 'Norway'
 'Paraguay' 'Poland' 'Portugal' 'Romania' 'Saint Kitts And Nevis'
 'Scotland' 'Senegal' 'Serbia' 'Slovakia' 'South Korea' 'Spain' 'Sweden'
 'Switzerland' 'The Democratic Republic Of Congo' 'Turkey' 'Ukraine'
 'United States' 'Uruguay' 'Wales' 'Zimbabwe']
[20 17 24 48 43 18 22 17 20 17  7  6  7 20 55 17 16 17 18 17 50 17 48 18
 19 11 17 17  7  7 17 17 37 12  2 56 17 17  5 18 16 17 17 17  7 43 17 17
 57 26 16 33 48 17  7 17 17  8  3 17 17 48 17 17 17 17  7 17 33 18 17 17
 17 30  2 20 17 17 33 10 17 26  5 49  5 18 25 10 26 41 49 17 36 17 17 17
 17 17 33 43 26 26 17 17 17 24 17 17 26

array([[2, 20, 28.0, ..., 0, 0, 0.0],
       [2, 17, 26.0, ..., 0, 0, 0.0],
       [2, 24, 25.0, ..., 0, 0, 0.0],
       ...,
       [1, 48, 24.0, ..., 0, 80, 13.0],
       [1, 40, 18.0, ..., 0, 0, 0.0],
       [1, 15, 20.0, ..., 0, 0, 0.0]], dtype=object)

In [204]:


X[:, 10] = np.array([float(value.rstrip('%')) for value in X[:, 10]])
X[;, 10]

array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '45%', '26%', '29%', '11%', '28%', '33%', '0%', '28%', '27%',
       '21%', '46%', '47%', '35%', '31%', '40%', '42%', '37%', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '15%', '0', '0',
       '32%', '35%', '3%', '30%', '14%', '33%', '33%', '38%', '17%', '0%',
       '51%', '29%', '3%', '35%', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '10%', '20%', '14%', '39%', '35%',
       '28%', '19%', '27%', '0%', '0%', '0%', '0%', '31%', '41%', '24%',
       '28%', '37%', '45%', '0%', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '31%', '32%', '8%', '27%', '27%', '25%',
       '0%', '47%', '38%', '37%', '54%', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0%', '39%', '24%', '29%',
       '24%', '18%', '36%', '41%', '1%', '0%', '17%', '42%', '39%', '28%',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',

In [ ]:

X[:, 10]
for i in X[:, 10]:
    if (type(i) == str):
        i = i[:-1]
        i = int(i)
        print(i)

45
26
29
11
28
33
0
28
27
21
46
47
35
31
40
42
37
15
32
35
3
30
14
33
33
38
17
0
51
29
3
35
10
20
14
39
35
28
19
27
0
0
0
0
31
41
24
28
37
45
0
31
32
8
27
27
25
0
47
38
37
54
0
39
24
29
24
18
36
41
1
0
17
42
39
28
38
21
32
31
30
26
4
0
0
35
35
38
31
0
34
25
37
19
0
25
0
100
25
30
27
11
33
30
39
43
42
41
29
42
17
32
16
1
21
50
23
21
50
0
38
34
31
45
21
100
0
27
1
100
0
33
0
0
0
45
50
0
25
34
30
29
32
38
31
21
18
16
24
26
33
0
49
40
42
41
33
28
38
30
43
29
27
50
33
36
100
34
1
43
43
45
25
0
44
2
39
21
0
27
36
36
37
29
44
100
0
0
41
54
41
43
0
37
37
39
36
21
40
47
26
35
100
46
43
41
49
33
30
25
31
33
39
27
50
25
46
100
0
32
29
45
37
40
34
25
35
33
29
28
0
4
0
52
41
43
30
36
20
41
41
27
34
6
50
40
40
32
40
19
34
24
32
38
40
44
1
28
0
16
34
0
43
45
44
37
25
26
29
0
0
17
1
38
0
38
47
50
42
36
0
1
41
31
35
34
30
36
24
0
0
38
45
22
48
2
0
19
25
39
23
41
0
0
32
35
27
0
0


In [ ]:
X[:, 10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '45%', '26%', '29%', '11%',
       '28%', '33%', '0%', '28%', '27%', '21%', '46%', '47%', '35%',
       '31%', '40%', '42%', '37%', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '15%',
       0, 0, '32%', '35%', '3%', '30%', '14%', '33%', '33%', '38%', '17%',
       '0%', '51%', '29%', '3%', '35%', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, '10%', '20%', '14%', '39%', '35%', '28%', '19%', '27%',
       '0%', '0%', '0%', '0%', '31%', '41%', '24%', '28%', '37%', '45%',
       '0%', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '31%', '32%', '8%',
       '27%', '27%', '25%', '0%', '47%', '38%', '37%', '54%', 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, '0%', '39%', '24%', '29%', '24%', '18%',
       '36%', '41%', '1%', '0%', '17%', '42%', '39%', '28%', 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '38%', '21%', '32%', '31%', 0,
       '30%', '26%', '4%', '0%', '0%', '35%', '35%', '38%', '31%', '0%',
       '34%', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '25%

In [ ]:
label_encoders = {}

# Apply label encoding to each column with string values in both training and test sets
for col in string_columns:
    label_encoders[col] = LabelEncoder()
    print(X[col])
    X[col] = label_encoders[col].fit_transform(X[col])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
for i in string_columns:
    index = string_columns.index(i)
    X[:, index] = le.fit_transform(X[:, index])

print(X)
    

TypeError: Encoders require their input argument must be uniformly strings or numbers. Got ['int', 'str']

In [ ]:

ct = ColumnTransformer(
    transformers=[
        ('encoder', LabelEncoder(), string_columns)
    ],
    remainder='passthrough'  # Passthrough any columns not specified in transformers
)
X = np.array(ct.fit_transform(X))

ValueError: Specifying the columns using strings is only supported for pandas DataFrames

Actually fitting the model:

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
label_encoders = {}

# Apply label encoding to each column with string values in both training and test sets
for col in string_columns:
    label_encoders[col] = LabelEncoder()
    X_train[col] = label_encoders[col].fit_transform(X_train[col])
    X_test[col] = label_encoders[col].transform(X_test[col])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices